# Generated by Django 4.1.7 on 2023-03-22 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='my_field',
            field=models.CharField(default='', max_length=100),
        ),
    ]
