# Generated by Django 4.1.7 on 2023-03-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_my_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='my_field',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
